command = "pacman"

[[match_err]]
pattern = [
	"no operation specified"
]
suggest = [
'''
#[length(1)]
{{command}} -Syu''',
'''
#[min_length(2)]
{{command[0]}} -S {{command[1:]}}''',
]

[[match_err]]
pattern = [
	"no targets specified"
]
suggest = [
'''
#[cmd_contains(-S)]
{{command[0]}} -Syu''',
]
